### PR TITLE
Crashlytics for all related crashes

### LINKED ISSUE #440: Crash on Profile Image Activity
There is a case where the `ProfileImageActivity` can crash.

```
Caused by java.lang.NullPointerException
       at org.gem.indo.dooit.views.onboarding.ProfileImageActivity$1.call(ProfileImageActivity.java:109)
       at org.gem.indo.dooit.views.onboarding.ProfileImageActivity$1.call(ProfileImageActivity.java:105)
```

The stacktrace does not indicate which reference is null. It is either the user or imageUri that is unexpectedly null.

Version 0.0.13

[See line 109 of ProfileImageActivity](https://github.com/praekeltfoundation/gem-bbb-indo/blob/develop/app/src/main/java/org/gem/indo/dooit/views/onboarding/ProfileImageActivity.java#L109)

[See stacktrace in Crashlytics issue #30](https://www.fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit/issues/587eaa830aeb16625b39a252)

### LINKED ISSUE #447: Crash on Goal Info View
`GoalInfoViewHolder` did not have a controller when it was instantiated.

```
Fatal Exception: org.gem.indo.dooit.models.exceptions.BotCallbackRequired: org.gem.indo.dooit.views.main.fragments.bot.viewholders.GoalInfoViewHolder requires adapter to have callback
       at org.gem.indo.dooit.views.main.fragments.bot.viewholders.GoalInfoViewHolder.<init>(GoalInfoViewHolder.java:56)
       at org.gem.indo.dooit.views.main.fragments.bot.adapters.BotAdapter.onCreateViewHolder(BotAdapter.java:80)
       at org.gem.indo.dooit.views.main.fragments.bot.adapters.BotAdapter.onCreateViewHolder(BotAdapter.java:38)
```

[See Crashlytics issue #32](https://www.fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit/issues/5880236b0aeb16625b44ba14)

1 Hour to investigate
1 Hour to fix/discuss

### PR DESCRIPTION
**Pull request by FredJEhlers**
fixes #440 
fixes #447 
@wvictor-rr have a look and let me know if there are more cases I should cover

### CODE REVIEW

File: app/src/main/java/org/gem/indo/dooit/helpers/crashlytics/crashlyticsHelper.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+import com.crashlytics.android.Crashlytics;
+
+import org.gem.indo.dooit.BuildConfig;
+
+/**
+ * Created by frede on 2017/01/23.
+ */
+
+public class crashlyticsHelper {
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/helpers/crashlytics/crashlyticsHelper.java]: Why was this class named with a lower case c?

File: app/src/main/java/org/gem/indo/dooit/views/ImageActivity.java [hunk 2]
```diff
@@ -222,6 +232,7 @@ private void processImage(int requestCodes) {
         } catch (IOException e) {
             Toast.makeText(this, "Unable to do image rotation", Toast.LENGTH_LONG).show();
             Log.e(TAG, "Unable to create temporary downscaled image file", e);
+            crashlyticsHelper.log(this.getClass().getSimpleName()," processImage : ", "an IOException");
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/ImageActivity.java]: Use `Crashlytics.logException(e)` to log the stack trace to crashlytics. Use `Crashlytics.log` to record useful state up until the crash. Catching the exception and only logging "an IOException" means we're not going to get the stacktrace.

```java
try {
    myMethodThatThrows();
} catch (Exception e) {
    Crashlytics.logException(e);
}
```

https://docs.fabric.io/android/crashlytics/caught-exceptions.html

File: app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/BotFragment.java [hunk 3]
```diff
@@ -395,10 +396,13 @@ public void onItemClicked(Object item) {
             model.setType(BotMessageType.TEXT);
             getBotAdapter().removeItem(model);
             getBotAdapter().addItem(model);
+            crashlyticsHelper.log(this.getClass().getSimpleName(),"onItemClicked: ", "model: " + model.toString());
         }
 
-        if (shouldAdd(answer))
+        if (shouldAdd(answer)){
             getBotAdapter().addItem(answer);
+            crashlyticsHelper.log(this.getClass().getSimpleName(),"onItemClicked: ","answer: " + answer.toString());
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/BotFragment.java]: Log that an answer is being added to the adapter:

```java
crashlyticsHelper.log(this.getClass().getSimpleName(),"onItemClicked: ","adding to conversation: " + answer.toString());
```

File: app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/BotFragment.java [hunk 4]
```diff
@@ -395,10 +396,13 @@ public void onItemClicked(Object item) {
             model.setType(BotMessageType.TEXT);
             getBotAdapter().removeItem(model);
             getBotAdapter().addItem(model);
+            crashlyticsHelper.log(this.getClass().getSimpleName(),"onItemClicked: ", "model: " + model.toString());
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/BotFragment.java]: Log that a Model is being changed

```java
crashlyticsHelper.log(this.getClass().getSimpleName(),"onItemClicked: ", "changed: " + model.toString());
```

File: app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/viewholders/GoalInfoViewHolder.java [hunk 5]
```diff
@@ -52,8 +53,14 @@ public GoalInfoViewHolder(View itemView, BotAdapter botAdapter) {
...
         itemView.setBackground(ContextCompat.getDrawable(getContext(), R.drawable.bkg_carousel_card));
 
-        if (!botAdapter.hasController())
-            throw new BotCallbackRequired(String.format("%s requires adapter to have callback", TAG));
+        try {
+            if (!botAdapter.hasController())
+                throw new BotCallbackRequired(String.format("%s requires adapter to have callback", TAG));
+        }
+        catch (BotCallbackRequired e){
+            crashlyticsHelper.log(this.getClass().getSimpleName(),"GoalInfoViewHolder : ", "crash because botadapter had no controller");
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/main/fragments/bot/viewholders/GoalInfoViewHolder.java]: Add `Crashlytics.logException(e)`

File: app/src/main/java/org/gem/indo/dooit/views/main/fragments/challenge/fragments/ChallengePictureFragment.java [hunk 6]
```diff
@@ -320,10 +321,16 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
...
-                    image.setImageURI(imageUri);
+                try {
+                    imagePath = MediaUriHelper.getPath(getContext(), data.getData());
+                    imageUri = data.getData();
+                    if (image != null) {
+                        image.setImageURI(imageUri);
+                    }
+                }
+                catch (NullPointerException nullException){
+                    crashlyticsHelper.log(this.getClass().getSimpleName(),"onActivityResult :",
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/main/fragments/challenge/fragments/ChallengePictureFragment.java]: Add `Crashlytics.logException(nullException)`

File: app/src/main/java/org/gem/indo/dooit/views/onboarding/ProfileImageActivity.java [hunk 7]
```diff
@@ -106,9 +112,15 @@ public void onError(DooitAPIError error) {
             @Override
             public void call(Response<EmptyResponse> response) {
                 User user = persisted.getCurrentUser();
-                if(user != null && user.getProfile() != null && getImageUri() != null) {
+
+                try{
                     user.getProfile().setProfileImageUrl(getImageUri().toString());
                 }
+                catch (NullPointerException nullException){
+                    crashlyticsHelper.log(this.getClass().getSimpleName(),"uploadProfileImage :",String.format("User is null %s: ",
```
Comment (wvictor-rr) [inline app/src/main/java/org/gem/indo/dooit/views/onboarding/ProfileImageActivity.java]: Add `Crashlytics.logException(nullException)`

**Review by wvictor-rr — CHANGES_REQUESTED** [review]
Please add `Crashlytics.logException(e)` in the catch blocks. Otherwise the logs won't be uploaded to Crashlytics.

**Review by wvictor-rr — APPROVED** [review]

**Comment by wvictor-rr** [comment]
Fixes https://github.com/praekeltfoundation/gem-bbb-indo/issues/457
